bukdu7seong/FE

lib/router.js

page가 component로 되어있어서 page로 수정하였음

hotfix: fix typo

---

build/Dockerfile
build/docker-compose.yml
build/nginx.conf

브라우저에서 보다 쉽게 프론트 페이지 개발을 할 수 있도록 도커파일을 만들었습니다.
build 디렉토리에 들어가서 docker compose up -d 로 도커를 띄울 수 있고, docker compose down 으로 컨테이너를 삭제할 수 있어요.
이제 경로가 설정된 상태애서 새로고침을 해도 잘 로딩됩니다!

added: add docker build for check spa

---

game/Ball.js
game/CollisionDetector.js
game/Obstacle.js
game/PingPong.js
game/Player.js
game/Tournament.js
game/style.css

Game update

---

game/CollisionDetector.js
game/Obstacle.js
game/style.css

refactor: try to solve collision issue

---

css/sign-in.css
css/styles.css
index.html
lib/render/component.js
lib/render/render.js
lib/router/router.js
lib/state/state.js
lib/state/update.js
src/app.js
src/components/common/userBox.js
src/components/login/login.js
src/pages/login.js
src/utils/checkLogin.js
test/login.js
test/style.css

develop 브랜치에 login 기능을 머지합니다.
추가로 구현된 checkLogin 함수는, 페이지 이동 시 만약 accessToken이 세션스토리지에 없을 경우, login 페이지로 리다이렉트를 하도록 합니다.

merge: merge login

---

build/nginx.conf
index.html

index.html에서 소스를 참조할 때, 상대 경로가 아닌 절대 경로에서 파일을 찾아서 가져오도록 수정했습니다.

fix: fix multi path bug

---

lib/router/navigate.js
lib/router/router.js
src/app.js

- 404 페이지가 뜨는 경우, 콘솔 로그에 나타나는 에러를 수정했습니다(onRender가 정의되어 있지 않아서 발생)
- 처음 페이지에 들어오는 경우, 뒤로가기를 두 번 해야 페이지가 변경되는 문제가 다시 발생해서 수정했습니다
- login 이후에도 뒤로가기를 통해 login 경로로 들어가면 login 페이지가 나오는 문제를 수정했습니다(뒤로가기 시에도 로그인 상태를 체크해서 경로를 변경)

Fix route bug

---

index.html
src/app.js

bootstrap css 임포트를 삭제해버려서 다시 추가했습니다!

hotfix: add bootstrap css

---

src/components/login/sign_in.js

hotfix: fix sign in error

---

src/components/game/PingPong.js
src/components/game/Tournament.js
src/components/profile/language.js
src/pages/game.js
src/pages/tournament.js

토너먼트 승리(종료) 모달 다국어 적용.
다국어 함수 위치 변경

Multilingual

---

src/components/login/sign_in.js

[FEAT] 2FA 활성화 상태에서 로그인 문제 해결.

---

lib/router/router.js
src/components/login/sign_in.js
src/components/login/sign_up.js
src/components/login/twofa.js

route를 redirectRoute로 변경하고, 로그인 시 유저 정보를 가져오는 API를 변경했습니다.

modify: modify some login

---

lib/router/router.js
src/components/login/sign_in.js

그런데 rebase 잘못 해서 sign_in의 수정사항 일부가 커밋에 포함이 안 된 것 같아요...

fix: fix async problem

---

src/components/profile/modal/changeUserName.js
src/utils/error.js
src/utils/initUser.js
src/utils/logout.js
src/utils/success.js

error, success, logout에 대한 wrapper function을 만들고 이를 코드에 적용중입니다. logout이 필요하실 것 같아서...

add wrapper functions

---

src/components/profile/modal/changeUserImage.js

fix: finish changeUserImage modal

---

src/components/profile/language.js
src/components/profile/modal/change2FA.js
src/components/profile/modal/changePassword.js
src/components/profile/modal/unsubscribe.js
src/components/profile/profile.js
src/pages/profile.js

Profile setting

---

src/components/profile/modal/changeUserName.js
src/pages/game.js

develop에서 발생하는 import 에러를 수정합니다
username 변경하는 부분에서 유저 네임 중복 체크를 안해서 같이 올립니다.

hotfix: fix import error & check username exist

---

lib/router/navigate.js
lib/router/router.js
src/app.js
src/components/common/sidebar.js
src/components/login/sign_in.js
src/components/login/sign_up.js
src/components/login/twofa.js
src/utils/checkLogin.js

일단 현재 디벨롭에서 생긴 문제는 잘 해결되는 것 같은데, 앞으로도 잘 되기를...

fix: router 꼬임 해결

---

src/app.js

fix: fix duplicated sidebar call

---

src/components/profile/modal/viewAllRequest.js
src/components/profile/profile.js
src/components/profile/updateRequest.js

* view all에서도 친구 신청 허용 시 리스트가 안보이도록 수정
* request 변경 시 친구 목록에서도 변경 연결

fix: fix friend request view all & connect with request & friend

---

src/pages/profile.js
src/utils/initUser.js

language.js 경로가 profile이 아닌 language로 변경되었습니다

fix: change language path

---

src/components/login/signUp.js

hotfix: fix check username api path

---

src/components/common/initUser.js
src/components/profile/data/historyData.js
src/components/profile/profile.js
src/utils/token.js

42 OAuth login을 하시면 바로 접근할 수 있습니다!

hotfix: fix user access

---

src/components/common/initUser.js
src/components/login/formValidator.js
src/components/login/signIn.js
src/components/login/signUp.js
src/utils/api.js

signin 시 바로 로그아웃되는 문제가 있어서 커밋을 올려놓습니다!

hotfix & profile fix

---

src/components/language/language.js
src/components/profile/profile.js

language change mode change

---

src/components/language/language.js
src/components/profile/modal/inviteFriends.js

profile WIP

---

assets/css/login/sign-in.css
assets/html/privacyPolicy.html
src/components/common/initUser.js
src/components/profile/modal/inviteFriends.js
src/components/profile/modal/userProfile.js
src/components/profile/modal/viewAllFriends.js
src/components/profile/modal/viewAllRequest.js
src/components/profile/profile.js
src/pages/login/signUp.js
src/utils/validateInput.js

escapeHTML을 수정하고 privacy policy page를 업데이트했습니다

fix: fix escapeHtml

---

build/nginx.conf
src/components/login/oauth2/oauth2RedirectHandler.js
src/components/login/signIn.js
src/components/login/twofa.js
src/components/profile/data/friendData.js
src/components/profile/data/gameData.js
src/components/profile/data/historyData.js
src/components/profile/data/imageData.js
src/components/profile/data/requestData.js
src/components/profile/profile.js
src/pages/login/signIn.js
src/utils/token.js

fix: fix refresh token issue

---

src/components/login/twofa.js
src/components/profile/modal/unsubscribe.js
src/components/profile/modal/viewAllHistory.js
src/components/profile/profile.js
src/utils/token.js

* 토큰 만료 시 로그아웃 처리
* 히스토리에 점수 표시 추가
* 언서브스크라이브시 로그아웃
* 2fa 이메일 여러 번 방지

some changes

---

lib/render/replace.js
src/app.js
src/components/common/initUser.js
src/components/game/PingPong.js
src/components/game/Tournament.js
src/components/profile/updateRequest.js

app.js의 catch에 있는 콘솔 로그를 제외하고 모두 지웠습니다

remove console logs

---

src/components/login/signUp.js

signup 시 413, 415에 대해 에러 메세지 출력 후 login으로 가지 않고 리턴하도록 수정했습니다

fix: handle image cases in signup

---

src/components/profile/modal/inviteFriends.js

fix: fix maxlen in invite friend

---

src/app.js
src/components/game/game.js
src/env.js
src/pages/game.js
src/pages/tournament.js

* 토너먼트와 게임에서 이름 설정 조건을 변경(빈 문자 X, 중복 X)

hotfix: fix game & tournament name setting

---

assets/css/profile/friend-list.css
src/components/profile/data/friendData.js
src/components/profile/data/historyData.js
src/components/profile/data/requestData.js
src/components/profile/profile.js

Hotfix sort

---

src/components/profile/data/friendData.js
src/components/profile/data/historyData.js
src/components/profile/data/requestData.js
src/components/profile/modal/viewAllFriends.js
src/components/profile/modal/viewAllHistory.js
src/components/profile/modal/viewAllRequest.js
src/components/profile/profile.js

hotfix: fix sort problem

---

src/components/profile/modal/viewAllFriends.js
src/components/profile/modal/viewAllRequest.js

hotfix: fix list mistype

---

assets/css/profile/friend-list.css
assets/css/profile/friend-request.css
assets/css/profile/player-history.css
src/components/profile/modal/viewAllFriends.js
src/components/profile/modal/viewAllHistory.js
src/components/profile/modal/viewAllRequest.js

Hotfix last
